/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tessstander (https://sketchfab.com/tessstander)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/basic-movie-clap-board-518a346ad70d4ef6b90f6ce2b117b627
Title: Basic movie clap board
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Clapperboard = (props) => {
    const { nodes, materials } = useGLTF('models/clapperboard.glb')
    return (
        <group {...props} dispose={null} scale={1.5}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group position={[-3.612, -0.003, 1.368]} scale={3.853}>
                <primitive object={nodes.clap_arm_rootJoint} />
                <skinnedMesh
                    geometry={nodes.clap_board_0.geometry}
                    material={materials.clap_boad}
                    skeleton={nodes.clap_board_0.skeleton}
                />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('models/clapperboard.glb')

export default Clapperboard
