/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Bognar Gabriella (https://sketchfab.com/bogabria)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/envelope-62fafeedd3cd449393b35e96e4cff83e
Title: Envelope
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Envelope = (props) => {
  const { nodes, materials } = useGLTF('models/envelope.glb')
  return (
    <group {...props} dispose={null} scale={40} rotation={[Math.PI / 2, Math.PI, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.bortk}
        position={[0, 0.008, 0]}
      />
    </group>
  )
}

useGLTF.preload('models/envelope.glb')

export default Envelope