/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Issac Ghazanfar (https://sketchfab.com/sheshhh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-laptop-7ceb46a1425b475fa7f6bf192e01ed74
Title: MacBook Laptop
*/

import React, { useRef, useState } from 'react'
import { Float, useGLTF, useTexture, useVideoTexture } from '@react-three/drei'
import { a, useSpring } from '@react-spring/three'

const Laptop = (props) => {
  const { nodes, materials } = useGLTF('models/laptop.glb')

  const screenTxt = useVideoTexture('textures/project/portfolio-txt.mp4')

    const [hovered, setHovered] = useState(0);

    const { scaleSpring } = useSpring({
        scaleSpring: hovered,
        config: {
            mass: 5, tension: 400, friction: 50, precision: 0.0001
        }
    })

    const scaler = scaleSpring.to([0, 1], [1, 1.5])

  return (
    <Float intensity={1}>
        <a.group {...props} dispose={null} scale={scaler} onPointerEnter={() => setHovered(1)} onPointerLeave={() => setHovered(0)} onClick={() => window.location='/#experience'}>
            <group scale={0.04}>
                <group
                rotation={[Math.PI, 0, 0]}
                scale={[9.059, 7.172, 9.059]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube001_Material002_0.geometry}
                    material={materials['Material.002']}
                />
                <group
                    position={[0.001, -1.421, 1.468]}
                    rotation={[1.386, 0, 0]}
                    scale={[11.038, 11.143, 13.86]}>
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_Material004_0.geometry}
                    material={materials['Material.004']}
                    />
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_Material002_0.geometry}
                    material={materials['Material.002']}
                    />
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube_Material003_0.geometry}
                    material={materials['Material.003']}
                    >
                        <meshMatcapMaterial map={screenTxt} />
                    </mesh>
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Keyboard_Material001_0.geometry}
                    material={materials['Material.001']}
                    position={[0.024, -0.032, 0.48]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={[0.976, 0.976, 0.978]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube002_Material002_0.geometry}
                    material={materials['Material.002']}
                    position={[-0.01, -0.047, -0.739]}
                    rotation={[Math.PI / 2, 0, 0]}
                    scale={[1.035, 0.972, 0.968]}
                />
                </group>
            </group>
        </a.group>
    </Float>
    
  )
}

useGLTF.preload('models/laptop.glb')

export default Laptop

