/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: eeelabvisual (https://sketchfab.com/eeelabvisual)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/name-tag-85de2b00ba4b4578997834ddbc626449
Title: Name Tag
*/

import React, { useRef, useState } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { a, useSpring } from '@react-spring/three'

const NameTag = (props) => {
  const { nodes, materials } = useGLTF('models/name_tag.glb')

  const [hovered, setHovered] = useState(0);
  
    const texture = useTexture('textures/cube.png');

    const { scaleSpring } = useSpring({
        scaleSpring: hovered,
        config: {
        mass: 5, tension: 400, friction: 50, precision: 0.0001
        }
    })

    const scaler = scaleSpring.to([0, 1], [0.1, 0.15])

    return (
        <a.group {...props}
        dispose={null}
        scale={scaler}
        onPointerEnter={() => setHovered(1)}
        onPointerLeave={() => setHovered(0)}
        rotation={[0, 0, 0]}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.pCube14_Name_tag_leather_base_0.geometry}
                material={materials.Name_tag_leather_base}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.pCube14_Leather_inside_name_tag_0.geometry}
                material={materials.Leather_inside_name_tag}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.pCube14_Plastik_0.geometry}
                material={materials.Plastik}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.pCube14_Tali_0.geometry}
                material={materials.Tali}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.pCube14_Steel_0.geometry}
                material={materials.Steel}
            />
        </a.group>
    )
}

useGLTF.preload('/name_tag.glb')

export default NameTag