/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: diopieretti3d (https://sketchfab.com/diopieretti3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-pc-low-poly-set-pack-7eab0a9519e74bd5b1f9f480b2ddca8b
Title: Old PC Low Poly Set - Pack
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const OldPc = (props) => {
  const { nodes, materials } = useGLTF('models/old_pc.glb')

  return (
    <group {...props} dispose={null}>
      <group scale={0.01} position={[-1.5, -1, 0]} rotation={[0, Math.PI, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MonitorOn_MonitorOn_0.geometry}
          material={materials.MonitorOn}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Keyboard_Keyboard_Material_0.geometry}
          material={materials.Keyboard_Material}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mouse_Mouse_Material_0.geometry}
          material={materials.Mouse_Material}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Case_Case_Texture_0.geometry}
          material={materials.Case_Texture}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/old_pc.glb')

export default OldPc