/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: A.stark (https://sketchfab.com/a.stark)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grandmas-tv-dda8301215014f6fb1329679ee4cd2c9
Title: Grandma's TV
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const OldTv = (props) => {
    const { nodes, materials } = useGLTF('models/old_tv.glb')
    return (
        <group {...props} dispose={null} scale={0.1} position={[0, 1.5, 0]}>
            <group position={[-0.678, 0, -0.691]} rotation={[-Math.PI / 2, 0, 1.552]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                <group rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Corps_01_plastic_0.geometry}
                    material={materials.plastic}
                    />
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Corps_09_buttons_0.geometry}
                    material={materials.buttons}
                    />
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Corps_10_buttons_0.geometry}
                    material={materials.buttons}
                    />
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Corps_01__1__plastic_0.geometry}
                    material={materials.plastic}
                    />
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Corps_11_buttons_0.geometry}
                    material={materials.buttons}
                    />
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Corps_01__2__plastic_0.geometry}
                    material={materials.plastic}
                    />
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Corps_02__1__screen_0.geometry}
                    material={materials.screen}
                    position={[-0.006, 0, 0]}
                    />
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Corps_08_plastic_0.geometry}
                    material={materials.plastic}
                    />
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Corps_12_buttons_0.geometry}
                    material={materials.buttons}
                    />
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Corps_13_buttons_0.geometry}
                    material={materials.buttons}
                    />
                    <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Corps_14_buttons_0.geometry}
                    material={materials.buttons}
                    />
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Plane_goonies_0.geometry}
                    material={materials.goonies}
                    position={[-6.499, 1.206, 0]}
                    rotation={[0, 0, 1.571]}
                />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('models/old_tv.glb')

export default OldTv