/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: plaggy (https://sketchfab.com/plaggy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cc0-pencil-holder-af1d78cea5b74f7bbe524b51693ce725
Title: CC0 - Pencil Holder
*/

import React, { useRef, useState } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { a, useSpring } from '@react-spring/three'

const PencilHolder = (props) => {
    const { nodes, materials } = useGLTF('models/pencil_holder.glb')

    const [hovered, setHovered] = useState(0);

    const texture = useTexture('textures/cube.png');

    const { scaleSpring } = useSpring({
        scaleSpring: hovered,
        config: {
          mass: 5, tension: 400, friction: 50, precision: 0.0001
        }
    })

    const scaler = scaleSpring.to([0, 2], [7, 10])

    return (
        <a.group
            {...props}
            dispose={null}
            scale={scaler}
            onPointerEnter={() => setHovered(1)}
            onPointerLeave={() => setHovered(0)}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.PencilBlack_PencilBlack_0.geometry}
            material={materials.PencilBlack}
            position={[-0.004, 0.071, 0.005]}
            rotation={[-2.204, 1.019, -0.86]}
            scale={0.025}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cup_Cup_0.geometry}
            material={materials.material}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.025}
            >
                <meshMatcapMaterial matcap={texture}/>
            </mesh>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.PencilGrey_PencilGrey_0.geometry}
            material={materials.PencilGrey}
            position={[-0.021, 0.076, -0.021]}
            rotation={[3.028, -0.695, -0.073]}
            scale={0.025}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.PencilLightBlue_PencilLightBlue_0.geometry}
            material={materials.PencilLightBlue}
            position={[-0.026, 0.076, 0]}
            rotation={[Math.PI, 0, -0.175]}
            scale={0.025}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.PencilBlue_Blue_0.geometry}
            material={materials.Blue}
            position={[0.003, 0.075, 0.016]}
            rotation={[-2.868, -0.084, 0.024]}
            scale={0.025}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.PencilGreen_PencilGreen_0.geometry}
            material={materials.PencilGreen}
            position={[-0.026, 0.076, -0.009]}
            rotation={[Math.PI, 0.087, -0.141]}
            scale={0.025}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.PencilLightGreen_PencilLightGreen_0.geometry}
            material={materials.PencilLightGreen}
            position={[0.01, 0.075, 0.02]}
            rotation={[0, -1.396, 2.88]}
            scale={0.025}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.PencilYellow_PencilYellow_0.geometry}
            material={materials.PencilYellow}
            position={[-0.002, 0.075, 0.022]}
            rotation={[-2.88, 0, 0]}
            scale={0.025}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.PencilOrange_PencilOrange_0.geometry}
            material={materials.PencilOrange}
            position={[-0.003, 0.075, -0.022]}
            rotation={[2.876, 0.169, 0.046]}
            scale={0.025}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.PencilRed_PendilRed_0.geometry}
            material={materials.PendilRed}
            position={[-0.012, 0.071, 0.005]}
            rotation={[-2.456, 0.835, -0.545]}
            scale={0.025}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes['PencilViolett_Material_#50_0'].geometry}
            material={materials.Material_50}
            position={[0.027, 0.076, -0.002]}
            rotation={[Math.PI, -0.611, 0.175]}
            scale={0.025}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.PencilPink_PencilPink_0.geometry}
            material={materials.PencilPink}
            position={[0.021, 0.076, -0.018]}
            rotation={[Math.PI, 0.175, 0.175]}
            scale={0.025}
            />
        </a.group>
    )
}

useGLTF.preload('models/pencil_holder.glb')

export default PencilHolder