/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: pan.stasian (https://sketchfab.com/pan_stasian)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/slightly-used-telephone-c0ec549c914545a8bb29620b70491afd
Title: Slightly used telephone
*/

import React, { useRef, useState } from 'react'
import { useGLTF, Float } from '@react-three/drei'
import { a, useSpring } from '@react-spring/three';

export default function Phone(props) {
    const { nodes, materials } = useGLTF('models/telephone.glb')

    const [hovered, setHovered] = useState(0);

    const { scaleSpring } = useSpring({
        scaleSpring: hovered,
        config: {
            mass: 5, tension: 400, friction: 50, precision: 0.0001
        }
    })

    const scaler = scaleSpring.to([0, 1], [0.5, 0.7])

    return (
        <Float intensity={1}>
            <a.group {...props} dispose={null} scale={scaler} rotation={[0, -Math.PI / 2, 0]} onPointerEnter={() => setHovered(1)} onPointerLeave={() => setHovered(0)} onClick={() => window.location='/#contact'}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.disc_lp_gold_0.geometry}
                    material={materials.gold}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.wire_lp_wire_mat_0.geometry}
                    material={materials.wire_mat}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.holder_lp_pink_0.geometry}
                    material={materials.pink}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.holder_lp_white_plastic_0.geometry}
                    material={materials.white_plastic}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.holder_lp_gold_0.geometry}
                    material={materials.gold}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.holder_lp_Dial_0.geometry}
                    material={materials.Dial}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.telephone_lp_pink_0.geometry}
                    material={materials.pink}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.legs_lp_white_plastic_0.geometry}
                    material={materials.white_plastic}
                />
            </a.group>
        </Float>
    )
}

useGLTF.preload('models/telephone.glb')
