/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: @sanyabeast (https://sketchfab.com/sanchibbo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/archive-sm-retrotv-01-a-64e61bf3cb704534bcaa3dea5fa2516d
Title: 🗿 [Archive] SM RetroTV 01 A
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useTexture, useVideoTexture } from '@react-three/drei'
import { useGSAP } from '@gsap/react'
import gsap from 'gsap'

const RetroTV = (props) => {
    const { nodes, materials } = useGLTF('models/retro_tv2.glb')

    const group = useRef()

    // Video Texture
    const videoTxt = useVideoTexture(props.texture ? props.texture : '/textures/project/portfolio-txt.mp4')

    useEffect( () => {
        if (videoTxt) {
            videoTxt.flipY = true;
        }
    }, [videoTxt] // Whenever texture changes
    )

    // Add animation for texture change
    useGSAP(() => {
        gsap.from(group.current.rotation, {
            y: Math.PI / 2,
            duration: 1,
            ease: 'power3.out'
        })
    }, [videoTxt])

    const screenTxt = useTexture('textures/screenTexture2.png')

    return (
        <group ref={group} {...props} dispose={null} scale={0.007} position={[0, 0.5, 0]}>
            <group
                position={[0.326, 179.304, 19.149]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[156.157, 58.75, 108.12]}>
                <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube015_BODY_C_0.geometry}
                material={materials.BODY_A}
                />
                <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube015_BODY_A_0.geometry}
                material={materials.BODY_A}
                />
                <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube015_BODY_D_0.geometry}
                material={materials.BODY_D}
                />
                <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube015_BODY_GLOSSY_0.geometry}
                material={materials.BODY_GLOSSY}
                />
                <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube015_SCREEN_0.geometry}
                material={materials.SCREEN}
                >
                    <meshMatcapMaterial map={videoTxt} />
                </mesh>
                <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube015_BODY_B_0.geometry}
                material={materials.BODY_B}
                />
            </group>
        </group>
    )
}

useGLTF.preload('models/retro_tv2.glb')

export default RetroTV